Fix gen_gpio_defaults.py error
I'm hitting an error when modifying the GPIOs:

    ValueError: invalid literal for int() with base 10: '0\\[0\\]'

We shouldn't be touching the first 5 GPIOs, but create a regex that
captures just the integer without the bit so that we don't error
out.