Fix make ship
set_user_id.py needs to run from $CARAVEL_ROOT, otherwise it gives a
warning which ends up in the mag2gds_caravel.tcl script, and causing
make ship to fail:

Error:  Cannot find top-level RTL caravel_user_project/verilog/rtl/caravel.v.  Is this script being run in the project directory?